# Esercizi su numpy

<hr>

In [2]:
import numpy as np
import csv

<hr>

### Esercizio 1

Creare una funzione che inverta un ndarray monodimensionale, ovvero crei un array monodimensionale con gli stessi elementi dell'array di partenza in ordine inverso.

In [2]:
a = np.random.randint(0, 20, size=10)
a

array([ 1,  1,  4, 13, 18,  4,  4,  0, 11,  5])

In [3]:
np.flip(a)

array([ 5, 11,  0,  4,  4, 18, 13,  4,  1,  1])

<hr>

### Esercizio 2

Generare un array Numpy che contenga le posizioni dei primi 100 numeri primi all'interno dei numeri naturali.

In [4]:
def isPrime(num):
    res = True
    
    for i in range(2, int(num ** 0.5) + 1):
        if num % i == 0:
            res = False
            break
            
    return res

In [5]:
isPrime_v = np.vectorize(isPrime)
natural_n = np.arange(2, 1000)

In [6]:
(natural_n[isPrime_v(natural_n)])[:100] + 1

array([  3,   4,   6,   8,  12,  14,  18,  20,  24,  30,  32,  38,  42,
        44,  48,  54,  60,  62,  68,  72,  74,  80,  84,  90,  98, 102,
       104, 108, 110, 114, 128, 132, 138, 140, 150, 152, 158, 164, 168,
       174, 180, 182, 192, 194, 198, 200, 212, 224, 228, 230, 234, 240,
       242, 252, 258, 264, 270, 272, 278, 282, 284, 294, 308, 312, 314,
       318, 332, 338, 348, 350, 354, 360, 368, 374, 380, 384, 390, 398,
       402, 410, 420, 422, 432, 434, 440, 444, 450, 458, 462, 464, 468,
       480, 488, 492, 500, 504, 510, 522, 524, 542])

<hr>

### Esercizio 3

Generare un array Numpy contenente i primi 10 numeri di Fibonacci.

In [7]:
numbers = np.ones(11, dtype=int)
numbers

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [8]:
for i in range(2, 11):
    numbers[i] = numbers[i - 1] + numbers[i - 2]
numbers

array([ 1,  1,  2,  3,  5,  8, 13, 21, 34, 55, 89])

<hr>

### Esercizio 4

Creare una matrice 8x8 alternando 0 ed 1 (la prima cella è uno 0).

In [9]:
mat = np.ones((8, 8), dtype=int)
mat

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [10]:
mat[::2, ::2] = mat[1::2, 1::2] = 0
mat

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

<hr>

### Esercizio 5

Considerando l'array: Z = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ,11, 12, 13, 14], generare un array R = [[1, 2, 3, 4], [2, 3, 4, 5], [3, 4, 5, 6], ..., [11, 12, 13, 14]].

In [11]:
z = np.arange(1, 15)
z

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
indici = np.array([i + j for i in range(0, 11) for j in range (0, 4)])
indici

array([ 0,  1,  2,  3,  1,  2,  3,  4,  2,  3,  4,  5,  3,  4,  5,  6,  4,
        5,  6,  7,  5,  6,  7,  8,  6,  7,  8,  9,  7,  8,  9, 10,  8,  9,
       10, 11,  9, 10, 11, 12, 10, 11, 12, 13])

In [13]:
r = z[indici].reshape((11, 4))
r

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

<hr>

### Esercizio 6

Usando la funzione numpy.random.normal(mean, dev, shape) generare un ndarray che contenga la stima dell'altezza degli alunni della classe. L'ndarray deve avere lunghezza pari al numero di compagni di classe. I valori mead e dev devono essere stimati in modo tale da simulare la distribuzione dell'altezza degli alunni in cm nel modo più realistico possibile.

In [14]:
vet = np.random.normal(loc=170, scale=9, size=30)
vet

array([188.34916566, 173.25834289, 158.89959785, 185.98067539,
       166.94727499, 161.97024147, 178.78144892, 167.20220726,
       175.11337044, 184.251673  , 170.68360358, 189.72870237,
       176.68810024, 163.22985277, 154.47624498, 171.42397734,
       162.57594233, 168.4393083 , 156.08959573, 174.80453862,
       161.2344972 , 179.20131016, 168.9654165 , 176.04588939,
       167.06295658, 174.98048827, 180.91164207, 187.48725445,
       171.92194483, 170.68847528])

<hr>

### Esercizio 7

Creare una matrice fatta come un bersaglio 10x10, le cornici concentriche hanno valori crescenti verso il centro (quella più esterna ha valori = 1).

In [15]:
mat = np.ones((10, 10), dtype=int)
mat

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [16]:
for i in range(1, 10 // 2):
    mat[i:-i, i:-i] = i + 1
mat

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 2, 2, 2, 2, 2, 2, 2, 2, 1],
       [1, 2, 3, 3, 3, 3, 3, 3, 2, 1],
       [1, 2, 3, 4, 4, 4, 4, 3, 2, 1],
       [1, 2, 3, 4, 5, 5, 4, 3, 2, 1],
       [1, 2, 3, 4, 5, 5, 4, 3, 2, 1],
       [1, 2, 3, 4, 4, 4, 4, 3, 2, 1],
       [1, 2, 3, 3, 3, 3, 3, 3, 2, 1],
       [1, 2, 2, 2, 2, 2, 2, 2, 2, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

<hr>

### Esercizio 8

Usiamo Numpy per creare dei dati simulati riferiti ad una situazione reale: in certi casi i dati simulati sono una buona approssimazione della realtà. Nel parco vicino alla scuola è installata una centralina per la misurazione del livello di polveri sottili PM10 nell'aria. Talvolta la centralina va in uno stato di errore per cui la misurazione delle PM10 fallisce ed il dato corrispondente riporta il valore 9999.9 all'interno dell'array delle misurazioni dati. Creare un array di 1000 campioni che generino dei valori secondo una distribuzione normale con valore medio 19 e varianza 5 e supporre che la centralina sia andata in errore 20 volte. La distribuzione gaussiana è una buona approssimazione dei dati reali della centralina?

In [17]:
campioni = np.random.normal(loc=19, scale=np.sqrt(5), size=1000)
campioni

array([20.7834003 , 18.63805981, 21.46447096, 15.07168826, 20.46229963,
       21.36929444, 20.6903295 , 18.99502649, 19.50304795, 19.26589279,
       14.66236366, 16.39346562, 21.62247919, 19.91086089, 16.83929302,
       18.92653734, 17.59608849, 19.07837342, 19.2226726 , 22.99671292,
       23.76947371, 18.06237325, 21.46800312, 20.76549468, 21.2211227 ,
       20.47668466, 20.42721708, 20.61459414, 16.4432363 , 19.80636941,
       18.2010822 , 21.57844314, 22.45485284, 20.09617255, 16.06507926,
       13.96961515, 22.62760704, 16.09464256, 23.70076111, 16.39550237,
       19.86256279, 18.43743867, 22.26007522, 16.6004008 , 19.40579448,
       24.29278649, 19.48601322, 18.91243428, 17.24828897, 19.52741475,
       19.00929863, 17.08798272, 26.1831363 , 19.93820312, 20.31868862,
       17.7699376 , 22.08287347, 15.97916502, 19.48388691, 23.31744077,
       22.22730125, 22.42222519, 17.78065414, 16.76777499, 17.0979894 ,
       19.57385244, 15.99343648, 17.68897752, 16.72819795, 16.45

In [18]:
campioni[np.random.choice(range(1000), 20, replace=False)] = 9999.99
campioni

array([  20.7834003 ,   18.63805981,   21.46447096,   15.07168826,
         20.46229963,   21.36929444,   20.6903295 ,   18.99502649,
       9999.99      ,   19.26589279,   14.66236366,   16.39346562,
         21.62247919,   19.91086089,   16.83929302,   18.92653734,
         17.59608849,   19.07837342,   19.2226726 ,   22.99671292,
         23.76947371,   18.06237325,   21.46800312,   20.76549468,
         21.2211227 ,   20.47668466,   20.42721708,   20.61459414,
         16.4432363 ,   19.80636941,   18.2010822 ,   21.57844314,
         22.45485284,   20.09617255,   16.06507926,   13.96961515,
         22.62760704,   16.09464256,   23.70076111,   16.39550237,
         19.86256279,   18.43743867,   22.26007522,   16.6004008 ,
         19.40579448,   24.29278649,   19.48601322,   18.91243428,
         17.24828897,   19.52741475,   19.00929863,   17.08798272,
         26.1831363 ,   19.93820312,   20.31868862,   17.7699376 ,
         22.08287347,   15.97916502,   19.48388691,   23.31744

In [19]:
np.count_nonzero(campioni == 9999.99)

20

<hr>

### Esercizio 9

Creare una funzione che trovi gli elementi comuni a due ndarray monodimensionali di lunghezza diversa.

In [20]:
a = np.random.randint(0, 100, size=(50,))
b = np.random.randint(0, 100, size=(35,))

In [21]:
a

array([77, 78, 93, 74,  3, 20, 56,  2, 49, 55, 42, 66, 16, 32, 75, 88, 26,
       57, 52, 85, 65,  8, 46,  5, 60,  6, 13, 83, 59,  5, 28, 43, 94, 82,
       10, 99, 26, 98, 89, 15, 64, 15, 19, 92, 90, 54,  3,  2,  6,  4])

In [22]:
b

array([ 4, 55, 83, 75, 31, 58, 57, 73,  9,  7, 98, 31, 66, 66, 97, 94,  0,
       73, 58, 24, 50, 50, 30, 58, 80, 79, 99, 87, 31, 35,  6, 22, 79,  3,
       20])

In [23]:
np.intersect1d(a, b)

array([ 3,  4,  6, 20, 55, 57, 66, 75, 83, 94, 98, 99])

<hr>

### Esercizio 10

Un braccio robotico industriale libero di muoversi avanti e indietro lungo una rotaia è impazzito. Ogni secondo si muove scegliendo a caso tra due possibili movimenti: 1 cm in avanti, oppure 1 cm indietro. Non è possibile togliere corrente al robot senza bloccare tutto lo stabilimento, quindi bisogna attendere lo spegnimento che si effettua tutti i finesettimana e oggi purtroppo è lunedì! Il nostro responsabile ci chiede di simulare lo spostamento totale che il robot avrà effettuato dopo 5 interi giorni di pazzia. Il robot è partito dalla posizione centrale della rotaia avente coordinata 0cm.

In [24]:
np.sum(np.random.choice((-1, 1), 5 * 24 * 60 * 60))

-688

<hr>

### Esercizio 11

Consideriamo mille classi da 25 alunni ciascuna: per ognuna di esse simuliamo il giorno di nascita di ciascun alunno estraendo un numero a caso tra 0 e 364 inclusi (i giorni dell'anno non bisestile sono 365): calcolare in quante delle mille classi ci sono almeno due alunni nati lo stesso giorno.

In [25]:
def duplicates(array):
    return len(np.unique(array)) == np.size(array)

np.count_nonzero(
    np.array(
        list(
            map(duplicates, np.random.randint(0, 365, size=(1000, 25)))
        )
    )
)

428

<hr>

### Esercizio 12

Dato un array monodimensionale di numeri, trovare la posizione di tutti i massimi locali. Ad esempio, dato l'array a = [0, 2, 1, 1, 3, 2], 2 e 3 sono massimi locali rispettivamente nelle posizioni 1 e 4.

In [26]:
cod = np.random.randint(0, 10 + 1, 10)
cod_1 = np.roll(cod, 1)
cod_2 = np.roll(cod, -1)

np.where((cod > cod_1) & (cod > cod_2))

(array([2, 4], dtype=int64),)

<hr>

### Esercizio 13

Dato un array monodimensionale di numeri interi compresi tra 0 e 9, generato casualmente, trovare le posizioni dell'array in cui compare la sequenza di numeri [1, 2, 3].

In [27]:
arr = np.random.randint(0, 10, 10000)
arr_1 = np.roll(arr, -1)
arr_2 = np.roll(arr, -2)

np.where((arr == 1) & (arr_1 == 2) & (arr_2 == 3))

(array([1878, 2168, 2178, 2473, 3637, 4155, 5092, 6386, 7529, 9152],
       dtype=int64),)

<hr>

### Esercizio 14

Sul territorio comunale sono installate tre centraline per la misurazione del livello di polveri sottili PM10 nell'aria. Talvolta le centraline vanno in uno stato di errore per cui la misurazione delle PM10 fallisce ed il dato corrispondente riporta il valore 9999.9 all'interno dell'array delle misurazioni. Inoltre, per motivi sconosciuti, talvolta le centraline riportano il valore -1. Statisticamente si è visto che il primo errore ha una frequenza dello 0.2% mentre il secondo del 0.1%

- Creare una matrice avente 3 colonne e le righe contenente i dati di tutte le centraline registrati nelle 24 ore (si registra il dato ogni minuto)
- Eliminare tutte le righe della matrice in cui vi sia almeno una misura errata o una misura di origine sconosciuta

In [28]:
n_mis = 24 * 60

mat = np.random.uniform(0, 100, size=(n_mis, 3))
mat

array([[42.16026553, 89.42643414, 87.71611982],
       [ 3.27595669, 78.81663314, 31.66789837],
       [12.30405728, 25.37227454, 28.37082349],
       ...,
       [93.70080626, 38.16335136, 16.75050909],
       [30.65198053, 23.88881998, 69.23860172],
       [58.74500817, 65.07878271, 62.64497347]])

In [29]:
mat[np.random.choice(range(n_mis), round(n_mis * 0.2/100), replace=False), np.random.randint(0, 3)] = 9999.99
mat[np.random.choice(range(n_mis), round(n_mis *0.1/100), replace=False), np.random.randint(0, 3)] = -1
mat

array([[42.16026553, 89.42643414, 87.71611982],
       [ 3.27595669, 78.81663314, 31.66789837],
       [12.30405728, 25.37227454, 28.37082349],
       ...,
       [93.70080626, 38.16335136, 16.75050909],
       [30.65198053, 23.88881998, 69.23860172],
       [58.74500817, 65.07878271, 62.64497347]])

In [30]:
np.count_nonzero(np.logical_or(mat == 9999.99, mat == -1))

4

In [31]:
res = np.copy(mat[np.logical_not(np.any(np.logical_or(mat == 9999.99, mat == -1), axis=1))])

In [32]:
np.count_nonzero(np.logical_or(res == 9999.99, res == -1))

0

<hr>

### Esercizio 15

Caricare i dati meteo dai file CSV e calcolare usando numpy:
- n° di giorni totali senza neve al suolo nelle due stazioni.
- n° di giorni nell'anno 2020 in cui la media delle temperature medie delle due stazioni è minore o uguale a zero.
- n° di giorni nell'anno 2019 in cui c'è neve al suolo e la temperatura media è maggiore di 0°C per entrambe le stazioni.

In [40]:
stazione1 = {
    "neve": {},
    "temperature": {}
}

stazione2 = {
    "neve": {},
    "temperature": {}
}

In [41]:
def readCSV(path, n_line_to_skip, dtypes):
    res = {}
    
    with open(path) as csv_file:
        #Vengono rimosse le prime righe che non fanno parte dei dati
        for _ in range(n_line_to_skip):
            csv_file.readline()
            
        csv_reader = csv.reader(csv_file, delimiter=",")
        
        for curr_line, row in enumerate(csv_reader):
            #Rimozioni caratteri di escape e blank a dx e sx in ogni stringa del record
            row = [s.strip() for s in row]

            if curr_line == 0:
                #Prima linea -> nomi delle colonne
                res = {header: np.zeros(0) for header in row}
            elif '' in row:
                #Record contenenti errori
                continue
            else:
                for i, field in enumerate(row):
                    """f_type = dtypes[i] #Data type del campo letto (field)
                    
                    #Se il data type è numerico è field è vuoto allora viene scritto 0
                    if field == '' and (f_type is int or f_type is float):
                        field = '0'"""
                    
                    #Aggiunta e conversione del campo nell'array corrispondente
                    res[list(res.keys())[i]] = np.append(res[list(res.keys())[i]], dtypes[i](field))
    
    #Rimozione ultima riga che non fa parte dei dati
    res["data"] = res["data"][:-1]
                    
    return res

In [42]:
#Lettura dati
stazione1["temperature"] = readCSV('./richiesta_dati_gg_80749_parte1.csv', 9, [str, str, float, str, float, str, str, float, str])
stazione1["neve"] = readCSV('./richiesta_dati_gg_80749_parte2.csv', 9, [str, int, int])
stazione2["temperature"] = readCSV('./richiesta_dati_gg_80749_parte3.csv', 9, [str, str, float, str, float, str, str, float, str])
stazione2["neve"] = readCSV('./richiesta_dati_gg_80749_parte4.csv', 9, [str, int, int])

In [43]:
#Task 1 - Stazione 1

np.count_nonzero(stazione1["neve"]["neve al suolo (cm)"] == 0)

722

In [44]:
#Task 1 - Stazione 2

np.count_nonzero(stazione2["neve"]["neve al suolo (cm)"] == 0)

377

In [45]:
#Task 2 - Stazione 1

# np.core.defchararray.find(vet, sub)
# Funzione restituisce un array dove ogni elemento corrisponde a N od a -1 a seconda se la substring "sub" è presente nell'
# elemento corrispondente dell'aray "vet", o no.
# Se presente l'elemento è = ad N dove N è la posizione del primo carattere della substring nella stringa dell'elementi di vet.

np.count_nonzero(
    (np.char.find(stazione1["temperature"]["data"], "2020") != -1) &
    (stazione1["temperature"]["Tmed"] <= 0)
)

175

In [46]:
#Task 2 - Stazione 2

np.count_nonzero(
    (np.char.find(stazione2["temperature"]["data"], "2020") != -1) &
    (stazione2["temperature"]["Tmed"] <= 0)
)

79

In [51]:
#Task 3 - Stazione 1

#Dato che stazioneX["neve"] e stazioneX["temperature"] non hanno lo stesso numero di record (stazioneX["neve"] è + piccolo)
#allora si aggiunge in coda all'array di bool "stazione1["neve"]["neve al suolo (cm)"] > 0" un numero di elementi
#pari alla differenza dei record, dove ogni elemento è FALSE in modo tale che questi ultimi non vengano inclusi nel risultato

diff = np.abs(stazione1["neve"]["neve al suolo (cm)"].size - stazione1["temperature"]["data"].size)

np.count_nonzero(
    np.logical_and(
        np.logical_and(
            np.char.find(stazione1["temperature"]["data"], "2019") != -1,
            np.append(stazione1["neve"]["neve al suolo (cm)"] > 0, np.zeros(diff, dtype=bool))
        ),
        stazione1["temperature"]["Tmed"] > 0
    )
)

39

In [52]:
#Task 3 - Stazione 2

diff = np.abs(stazione2["neve"]["neve al suolo (cm)"].size - stazione2["temperature"]["data"].size)

np.count_nonzero(
    np.logical_and(
        np.logical_and(
            np.char.find(stazione2["temperature"]["data"], "2019") != -1,
            np.append(stazione2["neve"]["neve al suolo (cm)"] > 0, np.zeros(diff, dtype=bool))
        ),
        stazione2["temperature"]["Tmed"] > 0
    )
)

209